import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseFragment } from "parse5";
import { BRAND_COLORS } from "../src/review-palette.js";

const root = fileURLToPath(new URL("../", import.meta.url));
const start = "  <!-- brand:start -->";
const end = "  <!-- brand:end -->";
const allowed = {
  svg: new Set(["xmlns", "width", "height", "viewBox"]),
  rect: new Set(["width", "height", "rx", "fill"]),
  path: new Set(["d", "fill", "fill-rule"]),
};

export function brandOutputs(source, colors, html) {
  function children(node) {
    return (node.childNodes || []).filter((child) => {
      if (child.nodeName !== "#text") return true;
      if (child.value.trim()) throw new Error("Brand SVG must not contain text.");
      return false;
    });
  }
  const nodes = children(parseFragment(source));
  const svg = nodes[0];
  if (nodes.length !== 1 || svg.tagName !== "svg") throw new Error("Brand source must be one SVG.");
  function attributes(node) {
    const names = allowed[node.tagName];
    if (!names || node.attrs.some((attribute) => !names.has(attribute.name) ||
        (attribute.namespace && !(node.tagName === "svg" && attribute.name === "xmlns" &&
          attribute.namespace === "http://www.w3.org/2000/xmlns/")))) {
      throw new Error(`Unsupported brand SVG element or attribute: ${node.tagName || node.nodeName}`);
    }
    return Object.fromEntries(node.attrs.map(({ name, value }) => [name, value]));
  }
  const size = attributes(svg);
  if (size.xmlns !== "http://www.w3.org/2000/svg" || size.width !== "64" ||
      size.height !== "64" || size.viewBox !== "0 0 64 64") {
    throw new Error("Brand SVG must use a square 64 by 64 canvas and viewBox.");
  }
  const shapes = children(svg);
  if (shapes.length !== 2 || shapes[0].tagName !== "rect" || shapes[1].tagName !== "path") {
    throw new Error("Brand SVG must contain only its rounded tile and cutout path.");
  }
  const tile = attributes(shapes[0]);
  const bubble = attributes(shapes[1]);
  if (shapes.some((shape) => children(shape).length) || tile.width !== "64" ||
      tile.height !== "64" || tile.rx !== "14" || bubble["fill-rule"] !== "evenodd" ||
      !/^[MLHVQCSTAZmlhvqcstaz\d\s,.\-+]+$/.test(bubble.d || "")) {
    throw new Error("Invalid rounded brand tile or cutout geometry.");
  }
  for (const [name, value] of Object.entries(colors)) {
    if (!/^#[\da-f]{6}$/i.test(value)) throw new Error(`Invalid brand color: ${name}`);
  }
  if (tile.fill?.toUpperCase() !== colors.tile?.toUpperCase() ||
      bubble.fill?.toUpperCase() !== colors.bubble?.toUpperCase()) {
    throw new Error("Brand artwork colors must match the canonical brand palette.");
  }
  if (html.indexOf(start) < 0 || html.indexOf(start) !== html.lastIndexOf(start) ||
      html.indexOf(end) < html.indexOf(start) || html.indexOf(end) !== html.lastIndexOf(end)) {
    throw new Error("Chrome HTML must contain exactly one ordered brand region.");
  }
  const markup = '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">' +
    `<rect width="64" height="64" rx="14" fill="${colors.tile}"/>` +
    `<path d="${bubble.d.trim().replace(/\s+/g, " ")}" fill="${colors.bubble}" fill-rule="evenodd"/></svg>`;
  const uri = `data:image/svg+xml,${encodeURIComponent(markup)}`;
  return {
    uri,
    module: `// Generated by scripts/generate-brand.js. Do not edit.\nexport const brandIconDataUri = ${JSON.stringify(uri)};\n`,
    html: html.slice(0, html.indexOf(start)) + `${start}\n  <link rel="icon" type="image/svg+xml" href="${uri}">\n` +
      html.slice(html.indexOf(end)),
  };
}

export async function generateBrand({ check = false } = {}) {
  const htmlPath = path.join(root, "src", "chrome.html");
  const outputs = brandOutputs(
    await readFile(path.join(root, "src", "assets", "doc-review.svg"), "utf8"),
    BRAND_COLORS,
    await readFile(htmlPath, "utf8"),
  );
  for (const [file, content] of [
    [path.join(root, "src", "ui", "brand.generated.ts"), outputs.module],
    [htmlPath, outputs.html],
  ]) {
    let existing;
    try { existing = await readFile(file, "utf8"); }
    catch (error) { if (error.code !== "ENOENT") throw error; }
    if (existing === content) continue;
    if (check) throw new Error(`Stale generated brand output: ${path.relative(root, file)}`);
    await writeFile(file, content);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.some((argument) => argument !== "--check")) throw new Error("Usage: generate-brand.js [--check]");
  await generateBrand({ check: args.includes("--check") });
}
