import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = JSON.parse(fs.readFileSync(path.join(root, "node_modules", "lucide-static", "icon-nodes.json"), "utf8"));
const icons = {
  eye: "eye",
  pencil: "pencil",
  chevronDown: "chevron-down",
  messageSquarePlus: "message-square-plus",
  messages: "messages-square",
  send: "send",
  trash: "trash-2",
  moreHorizontal: "ellipsis",
  x: "x",
  check: "check",
  sun: "sun",
  moon: "moon",
};
const selected = Object.fromEntries(Object.entries(icons).map(([name, sourceName]) => [name, source[sourceName]]));
if (Object.values(selected).some((nodes) => !nodes)) throw new Error("Lucide icon allowlist is incomplete.");
const output = `// Generated by scripts/generate-icons.js from lucide-static. Do not edit.\n` +
`export const ICON_NODES = Object.freeze(${JSON.stringify(selected, null, 2)});\n\n` +
`const escape = (value) => String(value).replace(/[&<>"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]);\n\n` +
`export function iconMarkup(name, { title = "", className = "icon", size = 16 } = {}) {\n` +
`  const nodes = ICON_NODES[name];\n` +
`  if (!nodes) throw new Error(\`Unknown icon: \${name}\`);\n` +
`  const body = nodes.map(([tag, attrs]) => \`<\${tag} \${Object.entries(attrs).map(([key, value]) => \`\${key}="\${escape(value)}"\`).join(" ")}></\${tag}>\`).join("");\n` +
`  const label = title ? \` role="img" aria-label="\${escape(title)}"\` : ' aria-hidden="true"';\n` +
`  return \`<svg class="\${escape(className)}" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"\${label}>\${body}</svg>\`;\n` +
`}\n\n` +
`export function createIcon(name, options = {}) {\n` +
`  const template = document.createElement("template");\n` +
`  template.innerHTML = iconMarkup(name, options);\n` +
`  return template.content.firstElementChild;\n` +
`}\n`;
fs.writeFileSync(path.join(root, "src", "icons.js"), output);
